lib/barrelfish: remove unused variable from target/x86_32/pmap_target.c
Updating the compiler made scc build tests fail with:
../../lib/barrelfish/target/x86_32/pmap_target.c: In function 'modify_flags':
../../lib/barrelfish/target/x86_32/pmap_target.c:420:19: error: variable 'ret' set but not used [-Werror=unused-but-set-variable]
cc1: all warnings being treated as errors

The compiler is right, so I removed the unused variable.

The reason that we didn't see the same message on x86_{32,64} is that these
architectures set -Wno-unused-but-set-variable in their default flags.