posixcompat (dlfcn): improve C++ compatibility and document how to use.
Note: a minor API change was necessary to fix an incompatibility between C and
C++, which requires array sizes to be fixed:
    void bar(struct foo (*f)[], int size);

This results in the following error:
    error: parameter 'f' includes pointer to array of unknown bound 'foo []'
    error: cannot convert 'foo (*)[3]' to 'foo (*)[]' for argument '1' to 'void bar(foo (*)[], int)'

Instead we simply pass the array as a pointer to its first element:
    void bar(struct foo *f, int size);